server:
   port: 8058
   context-path: /diancan
   session:
     timeout: 20
   tomcat:
     uri-encoding: UTF-8
# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diancan
    name: diancan
    username: root
    password: 123qweASD
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: logging
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  # logging
