server:
   port: 8081
   context-path: /diancan
   session:
     timeout: 20
   tomcat:
     uri-encoding: UTF-8
# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diancan?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123qweASD
    driver-class-name: com.mysql.jdbc.Driver
    name: diancan
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: diancan
      grid-fs-database: diancan-GridFS
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  http:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB
# custom config
mongoConfig:
  fileDB:
    host: 127.0.0.1
    name: "diancan-GridFS"
    port: 27017
    userName: ""
    password: ""
  loggingDB:
    host: 127.0.0.1
    name: "logging"
    port: 27017
    userName: ""
    password: ""
  businessDB:
    host: 127.0.0.1
    name: "diancan"
    port: 27017
    userName: ""
    password: ""
  userCluster: false

