server:
   port: 8058
   context-path: /diancan
   session:
     timeout: 20
  tomcat:
      uri-encoding: UTF-8
# datasource
spring:
  datasource:
          url: jdbc:mysql//localhost:3306/diancan
    username: root
    password:
    name: mysql
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/logging
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true